version: 2

models:
  - name: fact_sales_order
    description: "Fact table for all sales orders with product and customer details"
    columns:
      - name: sales_order_id
        tests:
          - not_null
      - name: customer_id
        tests:
          - relationships:
              to: ref('dim_customer')
              field: customer_id
      - name: product_id
        tests:
          - relationships:
              to: ref('dim_product')
              field: product_id
      - name: order_date
        tests:
          - not_null




